"""empty message

Revision ID: d329c7092d56
Revises: 7c9953ece79b
Create Date: 2025-10-27 17:26:26.005417

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d329c7092d56"
down_revision = "7c9953ece79b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("comment", sa.Text(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_column("comment")

    # ### end Alembic commands ###
